///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutW
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutomationPracticeRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("8d9d87ce-a223-48c9-8d3d-fa136d34097d")]
    public partial class AutomationPracticeRepository : RepoGenBaseFolder
    {
        static AutomationPracticeRepository instance = new AutomationPracticeRepository();
        AutomationPracticeRepositoryFolders.MyStoreAppFolder _mystore;

        /// <summary>
        /// Gets the singleton class instance representing the AutomationPracticeRepository element repository.
        /// </summary>
        [RepositoryFolder("8d9d87ce-a223-48c9-8d3d-fa136d34097d")]
        public static AutomationPracticeRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutomationPracticeRepository() 
            : base("AutomationPracticeRepository", "/", null, 0, false, "8d9d87ce-a223-48c9-8d3d-fa136d34097d", ".\\RepositoryImages\\AutomationPracticeRepository8d9d87ce.rximgres")
        {
            _mystore = new AutomationPracticeRepositoryFolders.MyStoreAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8d9d87ce-a223-48c9-8d3d-fa136d34097d")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MyStore folder.
        /// </summary>
        [RepositoryFolder("9797fa9f-8afb-44b4-8fea-885302ad9460")]
        public virtual AutomationPracticeRepositoryFolders.MyStoreAppFolder MyStore
        {
            get { return _mystore; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class AutomationPracticeRepositoryFolders
    {
        /// <summary>
        /// The MyStoreAppFolder folder.
        /// </summary>
        [RepositoryFolder("9797fa9f-8afb-44b4-8fea-885302ad9460")]
        public partial class MyStoreAppFolder : RepoGenBaseFolder
        {
            AutomationPracticeRepositoryFolders.LoggedInAddressFolder _loggedinaddress;
            AutomationPracticeRepositoryFolders.FormFieldsFolder _formfields;
            RepoItemInfo _signinlinkInfo;
            RepoItemInfo _emailaddresstextboxInfo;
            RepoItemInfo _createanaccountbuttonInfo;
            RepoItemInfo _myaddressesInfo;
            RepoItemInfo _logmeoutInfo;

            /// <summary>
            /// Creates a new MyStore  folder.
            /// </summary>
            public MyStoreAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MyStore", "/dom[@domain='automationpractice.com']", parentFolder, 30000, null, false, "9797fa9f-8afb-44b4-8fea-885302ad9460", "")
            {
                _loggedinaddress = new AutomationPracticeRepositoryFolders.LoggedInAddressFolder(this);
                _formfields = new AutomationPracticeRepositoryFolders.FormFieldsFolder(this);
                _signinlinkInfo = new RepoItemInfo(this, "SignInLink", ".//header[#'header']/div[2]//nav/?/?/a[@innertext='Sign in']", "", 30000, null, "cc5ef586-0eea-476e-b06c-899ffc50343c");
                _emailaddresstextboxInfo = new RepoItemInfo(this, "EmailAddressTextBox", ".//input[#'email_create']", "", 30000, null, "4f981ec8-a53a-4620-8573-47df76daa67f");
                _createanaccountbuttonInfo = new RepoItemInfo(this, "CreateAnAccountButton", ".//button[#'SubmitCreate']/span[@innertext>'Create an account']", "", 30000, null, "15b27ba2-a599-4a1d-99ce-37199025211f");
                _myaddressesInfo = new RepoItemInfo(this, "MyAddresses", ".//div[#'center_column']/div/div[1]/ul/?/?/a[@title='Addresses']/span[@innertext='My addresses']", "", 30000, null, "dd546dca-decd-433c-82b2-2a9b248b1aef");
                _logmeoutInfo = new RepoItemInfo(this, "LogMeOut", ".//header[#'header']//nav/div[2]/a[@innertext='Sign out']", "", 30000, null, "3b694895-e253-4040-b59f-deafc421f7d8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9797fa9f-8afb-44b4-8fea-885302ad9460")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9797fa9f-8afb-44b4-8fea-885302ad9460")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SignInLink item.
            /// </summary>
            [RepositoryItem("cc5ef586-0eea-476e-b06c-899ffc50343c")]
            public virtual Ranorex.ATag SignInLink
            {
                get
                {
                    return _signinlinkInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SignInLink item info.
            /// </summary>
            [RepositoryItemInfo("cc5ef586-0eea-476e-b06c-899ffc50343c")]
            public virtual RepoItemInfo SignInLinkInfo
            {
                get
                {
                    return _signinlinkInfo;
                }
            }

            /// <summary>
            /// The EmailAddressTextBox item.
            /// </summary>
            [RepositoryItem("4f981ec8-a53a-4620-8573-47df76daa67f")]
            public virtual Ranorex.InputTag EmailAddressTextBox
            {
                get
                {
                    return _emailaddresstextboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The EmailAddressTextBox item info.
            /// </summary>
            [RepositoryItemInfo("4f981ec8-a53a-4620-8573-47df76daa67f")]
            public virtual RepoItemInfo EmailAddressTextBoxInfo
            {
                get
                {
                    return _emailaddresstextboxInfo;
                }
            }

            /// <summary>
            /// The CreateAnAccountButton item.
            /// </summary>
            [RepositoryItem("15b27ba2-a599-4a1d-99ce-37199025211f")]
            public virtual Ranorex.SpanTag CreateAnAccountButton
            {
                get
                {
                    return _createanaccountbuttonInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The CreateAnAccountButton item info.
            /// </summary>
            [RepositoryItemInfo("15b27ba2-a599-4a1d-99ce-37199025211f")]
            public virtual RepoItemInfo CreateAnAccountButtonInfo
            {
                get
                {
                    return _createanaccountbuttonInfo;
                }
            }

            /// <summary>
            /// The MyAddresses item.
            /// </summary>
            [RepositoryItem("dd546dca-decd-433c-82b2-2a9b248b1aef")]
            public virtual Ranorex.SpanTag MyAddresses
            {
                get
                {
                    return _myaddressesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The MyAddresses item info.
            /// </summary>
            [RepositoryItemInfo("dd546dca-decd-433c-82b2-2a9b248b1aef")]
            public virtual RepoItemInfo MyAddressesInfo
            {
                get
                {
                    return _myaddressesInfo;
                }
            }

            /// <summary>
            /// The LogMeOut item.
            /// </summary>
            [RepositoryItem("3b694895-e253-4040-b59f-deafc421f7d8")]
            public virtual Ranorex.ATag LogMeOut
            {
                get
                {
                    return _logmeoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The LogMeOut item info.
            /// </summary>
            [RepositoryItemInfo("3b694895-e253-4040-b59f-deafc421f7d8")]
            public virtual RepoItemInfo LogMeOutInfo
            {
                get
                {
                    return _logmeoutInfo;
                }
            }

            /// <summary>
            /// The LoggedInAddress folder.
            /// </summary>
            [RepositoryFolder("023a6185-ff3e-43f1-8a6a-2d26661d7881")]
            public virtual AutomationPracticeRepositoryFolders.LoggedInAddressFolder LoggedInAddress
            {
                get { return _loggedinaddress; }
            }

            /// <summary>
            /// The FormFields folder.
            /// </summary>
            [RepositoryFolder("3e5074db-19ca-4ca8-a21b-15518faad868")]
            public virtual AutomationPracticeRepositoryFolders.FormFieldsFolder FormFields
            {
                get { return _formfields; }
            }
        }

        /// <summary>
        /// The LoggedInAddressFolder folder.
        /// </summary>
        [RepositoryFolder("023a6185-ff3e-43f1-8a6a-2d26661d7881")]
        public partial class LoggedInAddressFolder : RepoGenBaseFolder
        {
            RepoItemInfo _boxitemlastitemInfo;
            RepoItemInfo _spantaglastnameInfo;
            RepoItemInfo _spantagfirstnameInfo;
            RepoItemInfo _spantagaddressInfo;
            RepoItemInfo _spantagcityInfo;
            RepoItemInfo _spantagstateInfo;
            RepoItemInfo _spantagpostcodeInfo;
            RepoItemInfo _spantagcountryInfo;
            RepoItemInfo _spantagmobileInfo;

            /// <summary>
            /// Creates a new LoggedInAddress  folder.
            /// </summary>
            public LoggedInAddressFolder(RepoGenBaseFolder parentFolder) :
                    base("LoggedInAddress", "", parentFolder, 0, null, false, "023a6185-ff3e-43f1-8a6a-2d26661d7881", "")
            {
                _boxitemlastitemInfo = new RepoItemInfo(this, "BoxItemLastItem", ".//div[#'center_column']/div[1]//ul", "", 30000, null, "5ab95e48-1c1b-4f46-bc06-5184f4c67a06");
                _spantaglastnameInfo = new RepoItemInfo(this, "SpanTagLastName", ".//div[#'center_column']/div[1]/div/div/ul/li[2]/span[2]", "", 30000, null, "20ccb64b-119d-4f3a-9f29-7ce2d7ab6a37");
                _spantagfirstnameInfo = new RepoItemInfo(this, "SpanTagFirstName", ".//div[#'center_column']/div[1]/div/div/ul/li[2]/span[1]", "", 30000, null, "074ae8cb-e0b2-48a9-b517-8bba546669af");
                _spantagaddressInfo = new RepoItemInfo(this, "SpanTagAddress", ".//div[#'center_column']/div[1]/div/div/ul/li[4]/span[1]", "", 30000, null, "56b2a52c-9767-4dbb-9113-f3da7629c089");
                _spantagcityInfo = new RepoItemInfo(this, "SpanTagCity", ".//div[#'center_column']/div[1]/div/div/ul/li[5]/span[1]", "", 30000, null, "0633b84c-9e96-42a0-b9f3-5e63731b359a");
                _spantagstateInfo = new RepoItemInfo(this, "SpanTagState", ".//div[#'center_column']/div[1]/div/div/ul/li[5]/span[2]", "", 30000, null, "810fec87-eb5f-4bae-ace0-ec89226d5588");
                _spantagpostcodeInfo = new RepoItemInfo(this, "SpanTagPostcode", ".//div[#'center_column']/div[1]/div/div/ul/li[5]/span[3]", "", 30000, null, "175e39af-1547-4673-ab4d-bce35069dc7e");
                _spantagcountryInfo = new RepoItemInfo(this, "SpanTagCountry", ".//div[#'center_column']/div[1]/div/div/ul/li[6]/span", "", 30000, null, "636bb102-b182-45a8-b451-270abf131d90");
                _spantagmobileInfo = new RepoItemInfo(this, "SpanTagMobile", ".//div[#'center_column']/div[1]/div/div/ul/li[8]/span", "", 30000, null, "706dcb2a-9b25-4ebd-94f4-852172306b18");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("023a6185-ff3e-43f1-8a6a-2d26661d7881")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BoxItemLastItem item.
            /// </summary>
            [RepositoryItem("5ab95e48-1c1b-4f46-bc06-5184f4c67a06")]
            public virtual Ranorex.UlTag BoxItemLastItem
            {
                get
                {
                    return _boxitemlastitemInfo.CreateAdapter<Ranorex.UlTag>(true);
                }
            }

            /// <summary>
            /// The BoxItemLastItem item info.
            /// </summary>
            [RepositoryItemInfo("5ab95e48-1c1b-4f46-bc06-5184f4c67a06")]
            public virtual RepoItemInfo BoxItemLastItemInfo
            {
                get
                {
                    return _boxitemlastitemInfo;
                }
            }

            /// <summary>
            /// The SpanTagLastName item.
            /// </summary>
            [RepositoryItem("20ccb64b-119d-4f3a-9f29-7ce2d7ab6a37")]
            public virtual Ranorex.SpanTag SpanTagLastName
            {
                get
                {
                    return _spantaglastnameInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagLastName item info.
            /// </summary>
            [RepositoryItemInfo("20ccb64b-119d-4f3a-9f29-7ce2d7ab6a37")]
            public virtual RepoItemInfo SpanTagLastNameInfo
            {
                get
                {
                    return _spantaglastnameInfo;
                }
            }

            /// <summary>
            /// The SpanTagFirstName item.
            /// </summary>
            [RepositoryItem("074ae8cb-e0b2-48a9-b517-8bba546669af")]
            public virtual Ranorex.SpanTag SpanTagFirstName
            {
                get
                {
                    return _spantagfirstnameInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagFirstName item info.
            /// </summary>
            [RepositoryItemInfo("074ae8cb-e0b2-48a9-b517-8bba546669af")]
            public virtual RepoItemInfo SpanTagFirstNameInfo
            {
                get
                {
                    return _spantagfirstnameInfo;
                }
            }

            /// <summary>
            /// The SpanTagAddress item.
            /// </summary>
            [RepositoryItem("56b2a52c-9767-4dbb-9113-f3da7629c089")]
            public virtual Ranorex.SpanTag SpanTagAddress
            {
                get
                {
                    return _spantagaddressInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagAddress item info.
            /// </summary>
            [RepositoryItemInfo("56b2a52c-9767-4dbb-9113-f3da7629c089")]
            public virtual RepoItemInfo SpanTagAddressInfo
            {
                get
                {
                    return _spantagaddressInfo;
                }
            }

            /// <summary>
            /// The SpanTagCity item.
            /// </summary>
            [RepositoryItem("0633b84c-9e96-42a0-b9f3-5e63731b359a")]
            public virtual Ranorex.SpanTag SpanTagCity
            {
                get
                {
                    return _spantagcityInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagCity item info.
            /// </summary>
            [RepositoryItemInfo("0633b84c-9e96-42a0-b9f3-5e63731b359a")]
            public virtual RepoItemInfo SpanTagCityInfo
            {
                get
                {
                    return _spantagcityInfo;
                }
            }

            /// <summary>
            /// The SpanTagState item.
            /// </summary>
            [RepositoryItem("810fec87-eb5f-4bae-ace0-ec89226d5588")]
            public virtual Ranorex.SpanTag SpanTagState
            {
                get
                {
                    return _spantagstateInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagState item info.
            /// </summary>
            [RepositoryItemInfo("810fec87-eb5f-4bae-ace0-ec89226d5588")]
            public virtual RepoItemInfo SpanTagStateInfo
            {
                get
                {
                    return _spantagstateInfo;
                }
            }

            /// <summary>
            /// The SpanTagPostcode item.
            /// </summary>
            [RepositoryItem("175e39af-1547-4673-ab4d-bce35069dc7e")]
            public virtual Ranorex.SpanTag SpanTagPostcode
            {
                get
                {
                    return _spantagpostcodeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagPostcode item info.
            /// </summary>
            [RepositoryItemInfo("175e39af-1547-4673-ab4d-bce35069dc7e")]
            public virtual RepoItemInfo SpanTagPostcodeInfo
            {
                get
                {
                    return _spantagpostcodeInfo;
                }
            }

            /// <summary>
            /// The SpanTagCountry item.
            /// </summary>
            [RepositoryItem("636bb102-b182-45a8-b451-270abf131d90")]
            public virtual Ranorex.SpanTag SpanTagCountry
            {
                get
                {
                    return _spantagcountryInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagCountry item info.
            /// </summary>
            [RepositoryItemInfo("636bb102-b182-45a8-b451-270abf131d90")]
            public virtual RepoItemInfo SpanTagCountryInfo
            {
                get
                {
                    return _spantagcountryInfo;
                }
            }

            /// <summary>
            /// The SpanTagMobile item.
            /// </summary>
            [RepositoryItem("706dcb2a-9b25-4ebd-94f4-852172306b18")]
            public virtual Ranorex.SpanTag SpanTagMobile
            {
                get
                {
                    return _spantagmobileInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The SpanTagMobile item info.
            /// </summary>
            [RepositoryItemInfo("706dcb2a-9b25-4ebd-94f4-852172306b18")]
            public virtual RepoItemInfo SpanTagMobileInfo
            {
                get
                {
                    return _spantagmobileInfo;
                }
            }
        }

        /// <summary>
        /// The FormFieldsFolder folder.
        /// </summary>
        [RepositoryFolder("3e5074db-19ca-4ca8-a21b-15518faad868")]
        public partial class FormFieldsFolder : RepoGenBaseFolder
        {
            RepoItemInfo _addressfirstnameInfo;
            RepoItemInfo _idgenderInfo;
            RepoItemInfo _customerfirstnameInfo;
            RepoItemInfo _customerlastnameInfo;
            RepoItemInfo _passwdInfo;
            RepoItemInfo _address1Info;
            RepoItemInfo _phoneInfo;
            RepoItemInfo _phonemobileInfo;
            RepoItemInfo _registerInfo;
            RepoItemInfo _addresslastnameInfo;
            RepoItemInfo _cityInfo;
            RepoItemInfo _idstateInfo;
            RepoItemInfo _postcodeInfo;
            RepoItemInfo _aliasInfo;

            /// <summary>
            /// Creates a new FormFields  folder.
            /// </summary>
            public FormFieldsFolder(RepoGenBaseFolder parentFolder) :
                    base("FormFields", "", parentFolder, 0, null, false, "3e5074db-19ca-4ca8-a21b-15518faad868", "")
            {
                _addressfirstnameInfo = new RepoItemInfo(this, "AddressFirstname", ".//input[#'firstname']", "", 30000, null, "dba3bfb5-9678-41ce-a3b6-c895f806d9d9");
                _idgenderInfo = new RepoItemInfo(this, "IdGender", ".//form[#'account-creation_form']/div[1]/div[1]/?/?/label[@innertext='Mr.']//input[@name='id_gender']", "", 30000, null, "7e758cc7-9e93-4339-a56c-35ba119aff19");
                _customerfirstnameInfo = new RepoItemInfo(this, "CustomerFirstname", ".//input[#'customer_firstname']", "", 30000, null, "d180db83-084b-470f-985e-056741e4e1ca");
                _customerlastnameInfo = new RepoItemInfo(this, "CustomerLastname", ".//input[#'customer_lastname']", "", 30000, null, "21816162-e583-4b69-9bbd-014b7fb3edfa");
                _passwdInfo = new RepoItemInfo(this, "Passwd", ".//input[#'passwd']", "", 30000, null, "696b0ca8-abd1-45e4-9f06-2290fe237a19");
                _address1Info = new RepoItemInfo(this, "Address1", ".//form[#'account-creation_form']//input[@name='address1']", "", 30000, null, "f7d0427a-b34d-425a-a532-a1bc29d2da0a");
                _phoneInfo = new RepoItemInfo(this, "Phone", ".//input[#'phone']", "", 30000, null, "f0ad0e4f-f392-4027-a579-48efc262ef24");
                _phonemobileInfo = new RepoItemInfo(this, "PhoneMobile", ".//input[#'phone_mobile']", "", 30000, null, "59c409dd-b5d1-450c-9a65-e9610a759865");
                _registerInfo = new RepoItemInfo(this, "Register", ".//button[#'submitAccount']/span[@innertext='Register']", "", 30000, null, "d31d21df-a353-4b25-abc5-b5f4f598944a");
                _addresslastnameInfo = new RepoItemInfo(this, "AddressLastname", ".//input[#'lastname']", "", 30000, null, "5f84604a-b6a1-44b9-b72c-0ebdabd76f15");
                _cityInfo = new RepoItemInfo(this, "City", ".//input[#'city']", "", 30000, null, "f3c38ae8-9e50-4d1a-b251-7d0069c606d3");
                _idstateInfo = new RepoItemInfo(this, "IdState", ".//select[#'id_state']", "", 30000, null, "b72ad5bf-57a2-4999-9f80-e467a7f6c4cc");
                _postcodeInfo = new RepoItemInfo(this, "Postcode", ".//input[#'postcode']", "", 30000, null, "4f0e98e7-d0ac-4d2e-9e4b-91bf2f71ac4d");
                _aliasInfo = new RepoItemInfo(this, "Alias", ".//input[#'alias']", "", 30000, null, "f82af0b4-a69e-4505-9a57-af4cd2af8263");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3e5074db-19ca-4ca8-a21b-15518faad868")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The AddressFirstname item.
            /// </summary>
            [RepositoryItem("dba3bfb5-9678-41ce-a3b6-c895f806d9d9")]
            public virtual Ranorex.InputTag AddressFirstname
            {
                get
                {
                    return _addressfirstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AddressFirstname item info.
            /// </summary>
            [RepositoryItemInfo("dba3bfb5-9678-41ce-a3b6-c895f806d9d9")]
            public virtual RepoItemInfo AddressFirstnameInfo
            {
                get
                {
                    return _addressfirstnameInfo;
                }
            }

            /// <summary>
            /// The IdGender item.
            /// </summary>
            [RepositoryItem("7e758cc7-9e93-4339-a56c-35ba119aff19")]
            public virtual Ranorex.InputTag IdGender
            {
                get
                {
                    return _idgenderInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The IdGender item info.
            /// </summary>
            [RepositoryItemInfo("7e758cc7-9e93-4339-a56c-35ba119aff19")]
            public virtual RepoItemInfo IdGenderInfo
            {
                get
                {
                    return _idgenderInfo;
                }
            }

            /// <summary>
            /// The CustomerFirstname item.
            /// </summary>
            [RepositoryItem("d180db83-084b-470f-985e-056741e4e1ca")]
            public virtual Ranorex.InputTag CustomerFirstname
            {
                get
                {
                    return _customerfirstnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CustomerFirstname item info.
            /// </summary>
            [RepositoryItemInfo("d180db83-084b-470f-985e-056741e4e1ca")]
            public virtual RepoItemInfo CustomerFirstnameInfo
            {
                get
                {
                    return _customerfirstnameInfo;
                }
            }

            /// <summary>
            /// The CustomerLastname item.
            /// </summary>
            [RepositoryItem("21816162-e583-4b69-9bbd-014b7fb3edfa")]
            public virtual Ranorex.InputTag CustomerLastname
            {
                get
                {
                    return _customerlastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CustomerLastname item info.
            /// </summary>
            [RepositoryItemInfo("21816162-e583-4b69-9bbd-014b7fb3edfa")]
            public virtual RepoItemInfo CustomerLastnameInfo
            {
                get
                {
                    return _customerlastnameInfo;
                }
            }

            /// <summary>
            /// The Passwd item.
            /// </summary>
            [RepositoryItem("696b0ca8-abd1-45e4-9f06-2290fe237a19")]
            public virtual Ranorex.InputTag Passwd
            {
                get
                {
                    return _passwdInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Passwd item info.
            /// </summary>
            [RepositoryItemInfo("696b0ca8-abd1-45e4-9f06-2290fe237a19")]
            public virtual RepoItemInfo PasswdInfo
            {
                get
                {
                    return _passwdInfo;
                }
            }

            /// <summary>
            /// The Address1 item.
            /// </summary>
            [RepositoryItem("f7d0427a-b34d-425a-a532-a1bc29d2da0a")]
            public virtual Ranorex.InputTag Address1
            {
                get
                {
                    return _address1Info.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Address1 item info.
            /// </summary>
            [RepositoryItemInfo("f7d0427a-b34d-425a-a532-a1bc29d2da0a")]
            public virtual RepoItemInfo Address1Info
            {
                get
                {
                    return _address1Info;
                }
            }

            /// <summary>
            /// The Phone item.
            /// </summary>
            [RepositoryItem("f0ad0e4f-f392-4027-a579-48efc262ef24")]
            public virtual Ranorex.InputTag Phone
            {
                get
                {
                    return _phoneInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Phone item info.
            /// </summary>
            [RepositoryItemInfo("f0ad0e4f-f392-4027-a579-48efc262ef24")]
            public virtual RepoItemInfo PhoneInfo
            {
                get
                {
                    return _phoneInfo;
                }
            }

            /// <summary>
            /// The PhoneMobile item.
            /// </summary>
            [RepositoryItem("59c409dd-b5d1-450c-9a65-e9610a759865")]
            public virtual Ranorex.InputTag PhoneMobile
            {
                get
                {
                    return _phonemobileInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PhoneMobile item info.
            /// </summary>
            [RepositoryItemInfo("59c409dd-b5d1-450c-9a65-e9610a759865")]
            public virtual RepoItemInfo PhoneMobileInfo
            {
                get
                {
                    return _phonemobileInfo;
                }
            }

            /// <summary>
            /// The Register item.
            /// </summary>
            [RepositoryItem("d31d21df-a353-4b25-abc5-b5f4f598944a")]
            public virtual Ranorex.SpanTag Register
            {
                get
                {
                    return _registerInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Register item info.
            /// </summary>
            [RepositoryItemInfo("d31d21df-a353-4b25-abc5-b5f4f598944a")]
            public virtual RepoItemInfo RegisterInfo
            {
                get
                {
                    return _registerInfo;
                }
            }

            /// <summary>
            /// The AddressLastname item.
            /// </summary>
            [RepositoryItem("5f84604a-b6a1-44b9-b72c-0ebdabd76f15")]
            public virtual Ranorex.InputTag AddressLastname
            {
                get
                {
                    return _addresslastnameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The AddressLastname item info.
            /// </summary>
            [RepositoryItemInfo("5f84604a-b6a1-44b9-b72c-0ebdabd76f15")]
            public virtual RepoItemInfo AddressLastnameInfo
            {
                get
                {
                    return _addresslastnameInfo;
                }
            }

            /// <summary>
            /// The City item.
            /// </summary>
            [RepositoryItem("f3c38ae8-9e50-4d1a-b251-7d0069c606d3")]
            public virtual Ranorex.InputTag City
            {
                get
                {
                    return _cityInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The City item info.
            /// </summary>
            [RepositoryItemInfo("f3c38ae8-9e50-4d1a-b251-7d0069c606d3")]
            public virtual RepoItemInfo CityInfo
            {
                get
                {
                    return _cityInfo;
                }
            }

            /// <summary>
            /// The IdState item.
            /// </summary>
            [RepositoryItem("b72ad5bf-57a2-4999-9f80-e467a7f6c4cc")]
            public virtual Ranorex.SelectTag IdState
            {
                get
                {
                    return _idstateInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The IdState item info.
            /// </summary>
            [RepositoryItemInfo("b72ad5bf-57a2-4999-9f80-e467a7f6c4cc")]
            public virtual RepoItemInfo IdStateInfo
            {
                get
                {
                    return _idstateInfo;
                }
            }

            /// <summary>
            /// The Postcode item.
            /// </summary>
            [RepositoryItem("4f0e98e7-d0ac-4d2e-9e4b-91bf2f71ac4d")]
            public virtual Ranorex.InputTag Postcode
            {
                get
                {
                    return _postcodeInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Postcode item info.
            /// </summary>
            [RepositoryItemInfo("4f0e98e7-d0ac-4d2e-9e4b-91bf2f71ac4d")]
            public virtual RepoItemInfo PostcodeInfo
            {
                get
                {
                    return _postcodeInfo;
                }
            }

            /// <summary>
            /// The Alias item.
            /// </summary>
            [RepositoryItem("f82af0b4-a69e-4505-9a57-af4cd2af8263")]
            public virtual Ranorex.InputTag Alias
            {
                get
                {
                    return _aliasInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Alias item info.
            /// </summary>
            [RepositoryItemInfo("f82af0b4-a69e-4505-9a57-af4cd2af8263")]
            public virtual RepoItemInfo AliasInfo
            {
                get
                {
                    return _aliasInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
